name: A basic workflow

on: push

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: List Files
        run: ls -la
      - name: Print Working Directory
        run: pwd
      - name: Print Date
        run: date

  dependent_job:
    name: Dependent Job
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Confirm Dependency Execution
        run: echo "Build job completed for demo lab 3, now running dependent job."